services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ecommerce_api
        ports:
            - '127.0.0.1:5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
    dbgate:
        image: dbgate/dbgate
        environment:
            CONNECTIONS: CN1
            LABEL_CN1: postgres://postgres@postgres:5432/ecommerce_api
            SERVER_CN1: postgres
            USER_CN1: postgres
            PASSWORD_CN1: postgres
            PORT_CN1: 5432
            ENGINE_CN1: postgres@dbgate-plugin-postgres
        ports:
            - '127.0.0.1:5435:3000'
volumes:
    postgres_data: